server:
  tomcat:
    basedir: D:/upload/temp/
#dev环境  mysql8.0
fileScan:
  version:
    1.0.0
  auth:
    userName:
      wlpiaoyi
    password:
      123456
  fileMenu:
    E:/Videos/
#    D:\wlpia\Documents\Temp\suffix\