server:
  tomcat:
    basedir: D:/upload/temp/
#dev环境  mysql8.0
resource:
  ethName:
    wireless_32768
#    eth2
#    wlan0
  remoteIp:
  fileMenu:
#    E:/Videos/
    D:\wlpia\Documents\Temp\suffix\

# mongodb 日志级别
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO