server:
  tomcat:
    basedir: D:/upload/temp/
#dev环境  mysql8.0
resource:
  auth:
    userName:
      wlpiaoyi
    password:
      123456
  ethName:
    wireless_32768
#    eth2
#    wlan0
  remoteIp:
  fileMenu:
#    E:/Videos/
    D:\wlpia\Documents\Temp\suffix\