server:
  tomcat:
    basedir: temp/
#spring:
#  datasource:
#    url:
#      jdbc:sqlite:config/db/fileScan.db
#    username:
#    password:
#    driver-class-name:
#      org.sqlite.JDBC

mybatis:
  typeAliasesPackage:
    org.wlpiaoyi.framework.ee.fileScan.domain.**.entity
  mapperLocations:
    classpath*:**/mapper/**/*Mapper.xml

fileScan:
  version:
    1.0.0
  auth:
    userName:
      wlpiaoyi
    password:
      123456
  fileMenu:
    /Users
#    E:/Videos/
#    D:\wlpia\Documents\Temp\suffix\