server:
  tomcat:
    basedir: D:/upload/temp/
#dev环境  mysql8.0
resource:
  fileMenu:
    E:/Videos/

# mongodb 日志级别
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO