server:
  port: 8180
  tomcat:
    basedir: C:/Home/Document/Temp/tomcat/
#dev环境  mysql8.0
resource:
  fontName: "微软雅黑"
  dataPath:
    C:/Home/Document/Temp/upload/data/
  tempPath:
    C:/Home/Document/Temp/upload/temp
  aes:
    key:
      104ed7522903443d8b905223907eebbb2fa0978db6dd47d8b7d2c9cbef3b41eb
    iv:
      a1cd567E90123456
  sign:
    publicKey: |-
      MIIBuDCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2EbdSPO9EAMMeP4C2USZp
      RV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdrmVClpJ+f6AR7ECLCT7up1/63xhv4O1fn
      xqimFQ8E+4P208UewwI1VBNaFpEy9nXzrith1yrv8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmCouuE
      C/BYHPUCgYEA9+GghdabPd7LvKtcNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCBgLRJ
      FnEj6EwoFhO3zwkyjMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhRkImo
      g9/hWuWfBpKLZl6Ae1UlZAFMO/7PSSoDgYUAAoGBAMyDBLj55PknyzfXRfzByz3MDmt5FPwMN0HO
      00v6c3tV0l4E0oZuW/IOdXSF0TdTaa2jHQMarkPP5v8Mc83oZ50splFBJ6F0y+Jk7lvOh8bHTl46
      on5W0T7w8Qy8/LR8BZNVgcj9Mizcxd1eVKQAXIMgb6u2MZ8ryZEA+lWALOSd
    privateKey: |-
      MIIBSwIBADCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2EbdSPO9EAMMeP4C2
      USZpRV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdrmVClpJ+f6AR7ECLCT7up1/63xhv4
      O1fnxqimFQ8E+4P208UewwI1VBNaFpEy9nXzrith1yrv8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmC
      ouuEC/BYHPUCgYEA9+GghdabPd7LvKtcNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCB
      gLRJFnEj6EwoFhO3zwkyjMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhR
      kImog9/hWuWfBpKLZl6Ae1UlZAFMO/7PSSoEFgIULqGv+4HdEYM5CqUFM48ksAmDFko==
# mongodb 日志级别
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
spring:
  #  LOWER_CAMEL_CASE    userName    默认策略
  #  KEBAB_CASE    user-name
  #  LOWER_CASE    username
  #  SNAKE_CASE    user_name
  #  UPPER_CAMEL_CASE    UserName
  　jackson:
    　property-naming-strategy: LOWER_CAMEL_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.28.136.109:3306/resource_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 'zrgj@2025'
    initial-size: 10
    max-active: 100
    min-idle: 30
    max-wait: 40
    validation-query: SELECT 1
    druid:
      # MySql、PostgreSQL、SqlServer、DaMeng校验
      validation-query: select 1

  servlet:
    multipart:
      #设置总上传的数据大小
      max-request-size: 4096MB
      #单个文件大小
      maxFileSize : 1024MB
      #xx 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  #热部署模块
  devtools:
    restart:
      #热部署开关
      enabled: true
      #指定热部署的目录
      additional-paths: src/main/java
      #指定目录不更新
      exclude: test/**
# 在线文档配置
springdoc:
  swagger-ui:
    # 配置swagger-ui界面访问路径
    path: /swagger-ui.html
    # 包扫描路径
  packages-to-scan: org.wlpiaoyi.framework.ee.resource
  # 默认开启wend
  api-docs:
    enabled: true