url=jdbc:mysql://10.28.136.109:3306/resource_dev?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
databaseName=resource_dev
userName=root
password=zrgj@2025
packagePath=org.wlpiaoyi.framework.ee.resource
businessTag=biz
tablePrefix=res
tableNamePattern=res_%
projectName=resource
excludeColumns=id,create_user,create_time,update_time,update_user,status,create_dept,is_deleted,tenantId