# nohup java -Dfile.encoding=utf-8 -jar file.scan.jar --spring.config.location=config/application.file.scan.yml >> ./file.scan.log &

#tomcat config
server :
  port : 28080
  ##项目名字配置
  servlet :
    context-path : /
    #session过期
    session:
      timeout: PT4H
      #cookie:
      #  name: jxfgzs

  tomcat:
    basedir: /icss/project/zhzf/tomcat/
    uri-encoding : UTF-8
    #xx 报错修改的地方
    max-connections: 200000
    max-http-form-post-size: 9000000
    keep-alive-timeout: 60000
    threads:
      max: 128
      min-spare: 5
spring:
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    # 配置 Date 类的时区，如果不涉及可以不加
    time-zone: GMT+8
  # 环境 dev|test|prod
  profiles :
    active : dev


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
#dev环境  mysql8.0
resource:
  ethName:
    wlan0
  remoteIp:
    36.138.30.52
  fileMenu:
    /icss/project/zhzf/